apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcriber
  labels:
    app: transcriber
spec:
  replicas: 4
  selector:
    matchLabels:
      app: transcriber
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 8
  template:
    metadata:
      labels:
        app: transcriber
    spec:
      containers:
        - name: transcriber
          image: esayasn/sub-genie-transcriber
          envFrom:
            - configMapRef:
                name: transcriber-configmap
            - secretRef:
                name: transcriber-secret